# Generated by Django 2.0.3 on 2018-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('page_content', models.TextField()),
            ],
        ),
    ]
